name: Run Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ dev, main ]
jobs:
  test_code:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: 
          - macOS-latest
          - ubuntu-latest
        python-version:
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
    - uses: actions/checkout@v6
    - name: Install dependencies
      run: |
        if [[ "$(uname)" == *Darwin* ]]; then
          #curl -sSL https://raw.githubusercontent.com/legendu-net/icon/main/install_icon.sh | sudo bash -
          #icon docker -ic --user-to-docker ""
          brew install libmagic && brew link libmagic
        fi
        curl -LsSf https://astral.sh/uv/install.sh | sudo env UV_INSTALL_DIR="/usr/local/bin" sh
        uv sync --all-extras
    - name: Test with pytest
      run: uv run --python ${{ matrix.python-version }} pytest
