name: Lint Code

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint_code:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    container:
      image: dclong/rust-cicd
    steps:
    - uses: actions/checkout@v3
    #- uses: Swatinem/rust-cache@v2
    - name: Check Code Formatting
      run: |
        cargo fmt --all -- --check
    #- name: Lint Code Using Clippy
      #run: |
      #cargo clippy
