name: Test Code
on:
  pull_request:
    branches: [ dev, main ]
permissions:
  pull-requests: read
  contents: read
jobs:
  test_code:
    runs-on: ${{matrix.os}}
    #runs-on: self-hosted
    container:
      image: dclong/rust-cicd
      env:
        RUSTFLAGS: -Awarnings
        RUSTC_WRAPPER: ""
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          #- macOS-latest
    steps:
      - uses: actions/checkout@v3
      #- uses: Swatinem/rust-cache@v2
      - name: Run Test Cases
        run: |
          .github/workflows/test.py \
            --pr-number ${{ github.event.pull_request.number }} \
            --token ${{ secrets.ACTIONS_TOKEN }}
