name: Check Workflow Template Extensions

on:
  workflow_call:

jobs:
  check_workflow_template_extensions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Check workflow templates use .yaml extension
      run: |
        yml_files=$(find github_rest_api/scripts/github/workflows/ -name '*.yml')
        if [ -n "$yml_files" ]; then
          echo "The following workflow templates must use the .yaml extension instead of .yml:"
          echo "$yml_files"
          exit 1
        fi
