name: Create PR to dev
on:
  push:
    branches-ignore:
      - main
      - dev
      - gh-pages*
jobs:
  create_pr_to_dev:
    uses: legendu-net/.github/.github/workflows/create-pr-to-dev.yaml@main
    secrets: inherit
